### ISSUE TITLE
Messaging crashes when there are 2 nodes

### ISSUE THREAD

**Issue by allardy** [botpress/messaging#41]
When I start 2 servers and I speak with the bot on slack, I receive no answer and I get this stack trace on the first server I started (plus, messaging crashes and restarts).

![image](https://user-images.githubusercontent.com/42552874/126666438-2ac8b16d-bd2a-43f0-b7bc-a48c0ebbeac2.png)

Also, I think this log should be a debug log instead, since it has no use for the end user

![image](https://user-images.githubusercontent.com/42552874/126666808-da7b30bb-df02-4f47-addc-902709c10dbb.png)

**Comment by samuelmasse** [comment]
It looks like messaging isn't giving the correct INTERNAL_PASSWORD back to the process that started it

**Comment by samuelmasse** [comment]
The problem is that the different nodes are each setting the webhook url to be their localhost url (so one is setting it to `http://localhost:3000/api/v1/chat/receive` and the other is setting it to `http://localhost:3001/api/v1/chat/receive`). A way to solve this would be set the webhook to be the external url instead so that every node of messaging calls that same url. It still wouldn't work with the internal password as I suppose this password is created for every node

**Comment by allardy** [comment]
The internal password's purpose is to let the main process and subprocesses authenticate their communications. It is not intended to be used across multiple processes, we already have the `appSecret` when we need something globally accessible

**Comment by samuelmasse** [comment]
Fixed https://github.com/botpress/messaging/pull/46
